package hr.element.onebyseven.common.scalaCountries

abstract sealed class Country (
    alpha3: String,
    numeric3:  Int,
    wikiName: String)

case object AF extends Country("AFG",   4, "Afghanistan                                  ")
case object AX extends Country("ALA", 248, "Åland Islands                                ")
case object AL extends Country("ALB",   8, "Albania                                      ")
case object DZ extends Country("DZA",  12, "Algeria                                      ")
case object AS extends Country("ASM",  16, "American Samoa                               ")
case object AD extends Country("AND",  20, "Andorra                                      ")
case object AO extends Country("AGO",  24, "Angola                                       ")
case object AI extends Country("AIA", 660, "Anguilla                                     ")
case object AQ extends Country("ATA",  10, "Antarctica                                   ")
case object AG extends Country("ATG",  28, "Antigua and Barbuda                          ")
case object AR extends Country("ARG",  32, "Argentina                                    ")
case object AM extends Country("ARM",  51, "Armenia                                      ")
case object AW extends Country("ABW", 533, "Aruba                                        ")
case object AU extends Country("AUS",  36, "Australia                                    ")
case object AT extends Country("AUT",  40, "Austria                                      ")
case object AZ extends Country("AZE",  31, "Azerbaijan                                   ")
case object BS extends Country("BHS",  44, "Bahamas                                      ")
case object BH extends Country("BHR",  48, "Bahrain                                      ")
case object BD extends Country("BGD",  50, "Bangladesh                                   ")
case object BB extends Country("BRB",  52, "Barbados                                     ")
case object BY extends Country("BLR", 112, "Belarus                                      ")
case object BE extends Country("BEL",  56, "Belgium                                      ")
case object BZ extends Country("BLZ",  84, "Belize                                       ")
case object BJ extends Country("BEN", 204, "Benin                                        ")
case object BM extends Country("BMU",  60, "Bermuda                                      ")
case object BT extends Country("BTN",  64, "Bhutan                                       ")
case object BO extends Country("BOL",  68, "Bolivia, Plurinational State of              ")
case object BQ extends Country("BES", 535, "Bonaire, Sint Eustatius and Saba             ")
case object BA extends Country("BIH",  70, "Bosnia and Herzegovina                       ")
case object BW extends Country("BWA",  72, "Botswana                                     ")
case object BV extends Country("BVT",  74, "Bouvet Island                                ")
case object BR extends Country("BRA",  76, "Brazil                                       ")
case object IO extends Country("IOT",  86, "British Indian Ocean Territory               ")
case object BN extends Country("BRN",  96, "Brunei Darussalam                            ")
case object BG extends Country("BGR", 100, "Bulgaria                                     ")
case object BF extends Country("BFA", 854, "Burkina Faso                                 ")
case object BI extends Country("BDI", 108, "Burundi                                      ")
case object KH extends Country("KHM", 116, "Cambodia                                     ")
case object CM extends Country("CMR", 120, "Cameroon                                     ")
case object CA extends Country("CAN", 124, "Canada                                       ")
case object CV extends Country("CPV", 132, "Cape Verde                                   ")
case object KY extends Country("CYM", 136, "Cayman Islands                               ")
case object CF extends Country("CAF", 140, "Central African Republic                     ")
case object TD extends Country("TCD", 148, "Chad                                         ")
case object CL extends Country("CHL", 152, "Chile                                        ")
case object CN extends Country("CHN", 156, "China                                        ")
case object CX extends Country("CXR", 162, "Christmas Island                             ")
case object CC extends Country("CCK", 166, "Cocos (Keeling) Islands                      ")
case object CO extends Country("COL", 170, "Colombia                                     ")
case object KM extends Country("COM", 174, "Comoros                                      ")
case object CG extends Country("COG", 178, "Congo                                        ")
case object CD extends Country("COD", 180, "Congo, the Democratic Republic of the        ")
case object CK extends Country("COK", 184, "Cook Islands                                 ")
case object CR extends Country("CRI", 188, "Costa Rica                                   ")
case object CI extends Country("CIV", 384, "Côte d'Ivoire                                ")
case object HR extends Country("HRV", 191, "Croatia                                      ")
case object CU extends Country("CUB", 192, "Cuba                                         ")
case object CW extends Country("CUW", 531, "Curaçao                                      ")
case object CY extends Country("CYP", 196, "Cyprus                                       ")
case object CZ extends Country("CZE", 203, "Czech Republic                               ")
case object DK extends Country("DNK", 208, "Denmark                                      ")
case object DJ extends Country("DJI", 262, "Djibouti                                     ")
case object DM extends Country("DMA", 212, "Dominica                                     ")
case object DO extends Country("DOM", 214, "Dominican Republic                           ")
case object EC extends Country("ECU", 218, "Ecuador                                      ")
case object EG extends Country("EGY", 818, "Egypt                                        ")
case object SV extends Country("SLV", 222, "El Salvador                                  ")
case object GQ extends Country("GNQ", 226, "Equatorial Guinea                            ")
case object ER extends Country("ERI", 232, "Eritrea                                      ")
case object EE extends Country("EST", 233, "Estonia                                      ")
case object ET extends Country("ETH", 231, "Ethiopia                                     ")
case object FK extends Country("FLK", 238, "Falkland Islands (Malvinas)                  ")
case object FO extends Country("FRO", 234, "Faroe Islands                                ")
case object FJ extends Country("FJI", 242, "Fiji                                         ")
case object FI extends Country("FIN", 246, "Finland                                      ")
case object FR extends Country("FRA", 250, "France                                       ")
case object GF extends Country("GUF", 254, "French Guiana                                ")
case object PF extends Country("PYF", 258, "French Polynesia                             ")
case object TF extends Country("ATF", 260, "French Southern Territories                  ")
case object GA extends Country("GAB", 266, "Gabon                                        ")
case object GM extends Country("GMB", 270, "Gambia                                       ")
case object GE extends Country("GEO", 268, "Georgia                                      ")
case object DE extends Country("DEU", 276, "Germany                                      ")
case object GH extends Country("GHA", 288, "Ghana                                        ")
case object GI extends Country("GIB", 292, "Gibraltar                                    ")
case object GR extends Country("GRC", 300, "Greece                                       ")
case object GL extends Country("GRL", 304, "Greenland                                    ")
case object GD extends Country("GRD", 308, "Grenada                                      ")
case object GP extends Country("GLP", 312, "Guadeloupe                                   ")
case object GU extends Country("GUM", 316, "Guam                                         ")
case object GT extends Country("GTM", 320, "Guatemala                                    ")
case object GG extends Country("GGY", 831, "Guernsey                                     ")
case object GN extends Country("GIN", 324, "Guinea                                       ")
case object GW extends Country("GNB", 624, "Guinea-Bissau                                ")
case object GY extends Country("GUY", 328, "Guyana                                       ")
case object HT extends Country("HTI", 332, "Haiti                                        ")
case object HM extends Country("HMD", 334, "Heard Island and McDonald Islands            ")
case object VA extends Country("VAT", 336, "Holy See (Vatican City State)                ")
case object HN extends Country("HND", 340, "Honduras                                     ")
case object HK extends Country("HKG", 344, "Hong Kong                                    ")
case object HU extends Country("HUN", 348, "Hungary                                      ")
case object IS extends Country("ISL", 352, "Iceland                                      ")
case object IN extends Country("IND", 356, "India                                        ")
case object ID extends Country("IDN", 360, "Indonesia                                    ")
case object IR extends Country("IRN", 364, "Iran, Islamic Republic of                    ")
case object IQ extends Country("IRQ", 368, "Iraq                                         ")
case object IE extends Country("IRL", 372, "Ireland                                      ")
case object IM extends Country("IMN", 833, "Isle of Man                                  ")
case object IL extends Country("ISR", 376, "Israel                                       ")
case object IT extends Country("ITA", 380, "Italy                                        ")
case object JM extends Country("JAM", 388, "Jamaica                                      ")
case object JP extends Country("JPN", 392, "Japan                                        ")
case object JE extends Country("JEY", 832, "Jersey                                       ")
case object JO extends Country("JOR", 400, "Jordan                                       ")
case object KZ extends Country("KAZ", 398, "Kazakhstan                                   ")
case object KE extends Country("KEN", 404, "Kenya                                        ")
case object KI extends Country("KIR", 296, "Kiribati                                     ")
case object KP extends Country("PRK", 408, "Korea, Democratic People's Republic of       ")
case object KR extends Country("KOR", 410, "Korea, Republic of                           ")
case object KW extends Country("KWT", 414, "Kuwait                                       ")
case object KG extends Country("KGZ", 417, "Kyrgyzstan                                   ")
case object LA extends Country("LAO", 418, "Lao People's Democratic Republic             ")
case object LV extends Country("LVA", 428, "Latvia                                       ")
case object LB extends Country("LBN", 422, "Lebanon                                      ")
case object LS extends Country("LSO", 426, "Lesotho                                      ")
case object LR extends Country("LBR", 430, "Liberia                                      ")
case object LY extends Country("LBY", 434, "Libya                                        ")
case object LI extends Country("LIE", 438, "Liechtenstein                                ")
case object LT extends Country("LTU", 440, "Lithuania                                    ")
case object LU extends Country("LUX", 442, "Luxembourg                                   ")
case object MO extends Country("MAC", 446, "Macao                                        ")
case object MK extends Country("MKD", 807, "Macedonia, the former Yugoslav Republic of   ")
case object MG extends Country("MDG", 450, "Madagascar                                   ")
case object MW extends Country("MWI", 454, "Malawi                                       ")
case object MY extends Country("MYS", 458, "Malaysia                                     ")
case object MV extends Country("MDV", 462, "Maldives                                     ")
case object ML extends Country("MLI", 466, "Mali                                         ")
case object MT extends Country("MLT", 470, "Malta                                        ")
case object MH extends Country("MHL", 584, "Marshall Islands                             ")
case object MQ extends Country("MTQ", 474, "Martinique                                   ")
case object MR extends Country("MRT", 478, "Mauritania                                   ")
case object MU extends Country("MUS", 480, "Mauritius                                    ")
case object YT extends Country("MYT", 175, "Mayotte                                      ")
case object MX extends Country("MEX", 484, "Mexico                                       ")
case object FM extends Country("FSM", 583, "Micronesia, Federated States of              ")
case object MD extends Country("MDA", 498, "Moldova, Republic of                         ")
case object MC extends Country("MCO", 492, "Monaco                                       ")
case object MN extends Country("MNG", 496, "Mongolia                                     ")
case object ME extends Country("MNE", 499, "Montenegro                                   ")
case object MS extends Country("MSR", 500, "Montserrat                                   ")
case object MA extends Country("MAR", 504, "Morocco                                      ")
case object MZ extends Country("MOZ", 508, "Mozambique                                   ")
case object MM extends Country("MMR", 104, "Myanmar                                      ")
case object NA extends Country("NAM", 516, "Namibia                                      ")
case object NR extends Country("NRU", 520, "Nauru                                        ")
case object NP extends Country("NPL", 524, "Nepal                                        ")
case object NL extends Country("NLD", 528, "Netherlands                                  ")
case object NC extends Country("NCL", 540, "New Caledonia                                ")
case object NZ extends Country("NZL", 554, "New Zealand                                  ")
case object NI extends Country("NIC", 558, "Nicaragua                                    ")
case object NE extends Country("NER", 562, "Niger                                        ")
case object NG extends Country("NGA", 566, "Nigeria                                      ")
case object NU extends Country("NIU", 570, "Niue                                         ")
case object NF extends Country("NFK", 574, "Norfolk Island                               ")
case object MP extends Country("MNP", 580, "Northern Mariana Islands                     ")
case object NO extends Country("NOR", 578, "Norway                                       ")
case object OM extends Country("OMN", 512, "Oman                                         ")
case object PK extends Country("PAK", 586, "Pakistan                                     ")
case object PW extends Country("PLW", 585, "Palau                                        ")
case object PS extends Country("PSE", 275, "Palestinian Territory, Occupied              ")
case object PA extends Country("PAN", 591, "Panama                                       ")
case object PG extends Country("PNG", 598, "Papua New Guinea                             ")
case object PY extends Country("PRY", 600, "Paraguay                                     ")
case object PE extends Country("PER", 604, "Peru                                         ")
case object PH extends Country("PHL", 608, "Philippines                                  ")
case object PN extends Country("PCN", 612, "Pitcairn                                     ")
case object PL extends Country("POL", 616, "Poland                                       ")
case object PT extends Country("PRT", 620, "Portugal                                     ")
case object PR extends Country("PRI", 630, "Puerto Rico                                  ")
case object QA extends Country("QAT", 634, "Qatar                                        ")
case object RE extends Country("REU", 638, "Réunion                                      ")
case object RO extends Country("ROU", 642, "Romania                                      ")
case object RU extends Country("RUS", 643, "Russian Federation                           ")
case object RW extends Country("RWA", 646, "Rwanda                                       ")
case object BL extends Country("BLM", 652, "Saint Barthélemy                             ")
case object SH extends Country("SHN", 654, "Saint Helena, Ascension and Tristan da Cunha ")
case object KN extends Country("KNA", 659, "Saint Kitts and Nevis                        ")
case object LC extends Country("LCA", 662, "Saint Lucia                                  ")
case object MF extends Country("MAF", 663, "Saint Martin (French part)                   ")
case object PM extends Country("SPM", 666, "Saint Pierre and Miquelon                    ")
case object VC extends Country("VCT", 670, "Saint Vincent and the Grenadines             ")
case object WS extends Country("WSM", 882, "Samoa                                        ")
case object SM extends Country("SMR", 674, "San Marino                                   ")
case object ST extends Country("STP", 678, "Sao Tome and Principe                        ")
case object SA extends Country("SAU", 682, "Saudi Arabia                                 ")
case object SN extends Country("SEN", 686, "Senegal                                      ")
case object RS extends Country("SRB", 688, "Serbia                                       ")
case object SC extends Country("SYC", 690, "Seychelles                                   ")
case object SL extends Country("SLE", 694, "Sierra Leone                                 ")
case object SG extends Country("SGP", 702, "Singapore                                    ")
case object SX extends Country("SXM", 534, "Sint Maarten (Dutch part)                    ")
case object SK extends Country("SVK", 703, "Slovakia                                     ")
case object SI extends Country("SVN", 705, "Slovenia                                     ")
case object SB extends Country("SLB",  90, "Solomon Islands                              ")
case object SO extends Country("SOM", 706, "Somalia                                      ")
case object ZA extends Country("ZAF", 710, "South Africa                                 ")
case object GS extends Country("SGS", 239, "South Georgia and the South Sandwich Islands ")
case object SS extends Country("SSD", 728, "South Sudan                                  ")
case object ES extends Country("ESP", 724, "Spain                                        ")
case object LK extends Country("LKA", 144, "Sri Lanka                                    ")
case object SD extends Country("SDN", 729, "Sudan                                        ")
case object SR extends Country("SUR", 740, "Suriname                                     ")
case object SJ extends Country("SJM", 744, "Svalbard and Jan Mayen                       ")
case object SZ extends Country("SWZ", 748, "Swaziland                                    ")
case object SE extends Country("SWE", 752, "Sweden                                       ")
case object CH extends Country("CHE", 756, "Switzerland                                  ")
case object SY extends Country("SYR", 760, "Syrian Arab Republic                         ")
case object TW extends Country("TWN", 158, "Taiwan, Province of China                    ")
case object TJ extends Country("TJK", 762, "Tajikistan                                   ")
case object TZ extends Country("TZA", 834, "Tanzania, United Republic of                 ")
case object TH extends Country("THA", 764, "Thailand                                     ")
case object TL extends Country("TLS", 626, "Timor-Leste                                  ")
case object TG extends Country("TGO", 768, "Togo                                         ")
case object TK extends Country("TKL", 772, "Tokelau                                      ")
case object TO extends Country("TON", 776, "Tonga                                        ")
case object TT extends Country("TTO", 780, "Trinidad and Tobago                          ")
case object TN extends Country("TUN", 788, "Tunisia                                      ")
case object TR extends Country("TUR", 792, "Turkey                                       ")
case object TM extends Country("TKM", 795, "Turkmenistan                                 ")
case object TC extends Country("TCA", 796, "Turks and Caicos Islands                     ")
case object TV extends Country("TUV", 798, "Tuvalu                                       ")
case object UG extends Country("UGA", 800, "Uganda                                       ")
case object UA extends Country("UKR", 804, "Ukraine                                      ")
case object AE extends Country("ARE", 784, "United Arab Emirates                         ")
case object GB extends Country("GBR", 826, "United Kingdom                               ")
case object US extends Country("USA", 840, "United States                                ")
case object UM extends Country("UMI", 581, "United States Minor Outlying Islands         ")
case object UY extends Country("URY", 858, "Uruguay                                      ")
case object UZ extends Country("UZB", 860, "Uzbekistan                                   ")
case object VU extends Country("VUT", 548, "Vanuatu                                      ")
case object VE extends Country("VEN", 862, "Venezuela, Bolivarian Republic of            ")
case object VN extends Country("VNM", 704, "Viet Nam                                     ")
case object VG extends Country("VGB",  92, "Virgin Islands, British                      ")
case object VI extends Country("VIR", 850, "Virgin Islands, U.S.                         ")
case object WF extends Country("WLF", 876, "Wallis and Futuna                            ")
case object EH extends Country("ESH", 732, "Western Sahara                               ")
case object YE extends Country("YEM", 887, "Yemen                                        ")
case object ZM extends Country("ZMB", 894, "Zambia                                       ")
case object ZW extends Country("ZWE", 716, "Zimbabwe                                     ")


