DROP SCHEMA IF EXISTS iso CASCADE;

CREATE SCHEMA iso;
COMMENT ON SCHEMA iso IS 'ISO tables (read-only)';

CREATE TABLE iso.countries
(
	code text
		CONSTRAINT pk_iso_countries_code PRIMARY KEY WITH(FILLFACTOR=100)
		CONSTRAINT ck_iso_countries_code CHECK(code~'^[A-Z]{2}$'),
	name text NOT NULL
		CONSTRAINT uq_iso_countries_name UNIQUE WITH(FILLFACTOR=100),
	capital text
		CONSTRAINT ck_iso_countries_capital CHECK(capital<>'')
)
WITH(FILLFACTOR=100);

COMMENT ON TABLE iso.countries IS 'ISO 3166-1: Codes for countries, dependent territories, and special areas of geographical interest';
COMMENT ON COLUMN iso.countries.code IS 'PK: Two-letter country code';
COMMENT ON COLUMN iso.countries.name IS 'UQ: Country name';
COMMENT ON COLUMN iso.countries.capital IS 'Country capital';

ALTER TABLE iso.countries CLUSTER ON uq_iso_countries_name;

INSERT INTO iso.countries(code,name,capital)VALUES
( 'AF', 'Afganistan',                                'Kabul'                      ),
( 'AL', 'Albanija',                                  'Tirana'                     ),
( 'DZ', 'Alžir',                                     'Algiers'                    ),
( 'AS', 'Američka Samoa',                            'Pago Pago'                  ),
( 'VI', 'Američki Djevičanski Otoci',                'Charlotte Amalie'           ),
( 'AD', 'Andora',                                    'Andorra la Vella'           ),
( 'AO', 'Angola',                                    'Luanda'                     ),
( 'AI', 'Anguilla',                                  'The Valley'                 ),
( 'AQ', 'Antarktika',                                NULL                         ),
( 'AG', 'Antigva i Barbuda',                         'St. John''s'                ),
( 'AR', 'Argentina',                                 'Buenos Aires'               ),
( 'AM', 'Armenija',                                  'Yerevan'                    ),
( 'AW', 'Aruba',                                     'Oranjestad'                 ),
( 'AU', 'Australija',                                'Canberra'                   ),
( 'AT', 'Austrija',                                  'Vienna'                     ),
( 'AZ', 'Azerbajdžan',                               'Baku'                       ),
( 'BS', 'Bahami',                                    'Nassau'                     ),
( 'BH', 'Bahrein',                                   'Manama'                     ),
( 'BD', 'Bangladeš',                                 'Dhaka'                      ),
( 'BB', 'Barbados',                                  'Bridgetown'                 ),
( 'BE', 'Belgija',                                   'Brussels'                   ),
( 'BZ', 'Belize',                                    'Belmopan'                   ),
( 'BJ', 'Benin',                                     'Porto-Novo'                 ),
( 'BM', 'Bermudi',                                   'Hamilton'                   ),
( 'BY', 'Bjelorusija',                               'Minsk'                      ),
( 'BW', 'Bocvana',                                   'Gaborone'                   ),
( 'BO', 'Bolivija',                                  'Sucre'                      ),
( 'BA', 'Bosna i Hercegovina',                       'Sarajevo'                   ),
( 'CX', 'Božićni otok',                              'Flying Fish Cove'           ),
( 'BR', 'Brazil',                                    'Brasília'                   ),
( 'VG', 'Britanski Djevičanski Otoci',               'Road Town'                  ),
( 'IO', 'Britanski Indijskooceanski Teritorij',      'Diego Garcia'               ),
( 'BN', 'Brunej',                                    'Bandar Seri Begawan'        ),
( 'BG', 'Bugarska',                                  'Sofia'                      ),
( 'BF', 'Burkina Faso',                              'Ouagadougou'                ),
( 'BI', 'Burundi',                                   'Bujumbura'                  ),
( 'BT', 'Butan',                                     'Thimphu'                    ),
( 'TD', 'Čad',                                       'N''Djamena'                 ),
( 'CZ', 'Češka',                                     'Prague'                     ),
( 'CL', 'Čile',                                      'Santiago'                   ),
( 'CY', 'Cipar',                                     'Nicosia'                    ),
( 'ME', 'Crna Gora',                                 'Podgorica'                  ),
( 'DK', 'Danska',                                    'Copenhagen'                 ),
( 'DM', 'Dominika',                                  'Roseau'                     ),
( 'DO', 'Dominikanska Republika',                    'Santo Domingo'              ),
( 'DJ', 'Džibuti',                                   'Djibouti'                   ),
( 'EG', 'Egipat',                                    'Cairo'                      ),
( 'EC', 'Ekvador',                                   'Quito'                      ),
( 'GQ', 'Ekvatorska Gvineja',                        'Malabo'                     ),
( 'ER', 'Eritreja',                                  'Asmara'                     ),
( 'EE', 'Estonija',                                  'Tallinn'                    ),
( 'ET', 'Etiopija',                                  'Addis Ababa'                ),
( 'FK', 'Falklandi (Malvini)',                       'Stanley'                    ),
( 'FO', 'Ferojski otoci',                            'Tórshavn'                   ),
( 'FJ', 'Fidži',                                     'Suva'                       ),
( 'PH', 'Filipini',                                  'Manila'                     ),
( 'FI', 'Finska',                                    'Helsinki'                   ),
( 'FR', 'Francuska',                                 'Paris'                      ),
( 'GF', 'Francuska Gvajana',                         'Cayenne'                    ),
( 'PF', 'Francuska Polinezija',                      'Papeete'                    ),
( 'TF', 'Francuski južni teritoriji',                'Port-aux-Français'          ),
( 'GA', 'Gabon',                                     'Libreville'                 ),
( 'GM', 'Gambija',                                   'Banjul'                     ),
( 'GH', 'Gana',                                      'Accra'                      ),
( 'GI', 'Gibraltar',                                 'Gibraltar'                  ),
( 'GR', 'Grčka',                                     'Athens'                     ),
( 'GD', 'Grenada',                                   'St. George''s'              ),
( 'GL', 'Grenland',                                  'Nuuk'                       ),
( 'GE', 'Gruzija',                                   'Tbilisi'                    ),
( 'GP', 'Guadeloupe',                                'Basse-Terre'                ),
( 'GU', 'Guam',                                      'Hagåtña'                    ),
( 'GG', 'Guernsey',                                  'St. Peter Port'             ),
( 'GY', 'Gvajana',                                   'Georgetown'                 ),
( 'GT', 'Gvatemala',                                 'Guatemala City'             ),
( 'GN', 'Gvineja',                                   'Conakry'                    ),
( 'GW', 'Gvineja Bisau',                             'Bissau'                     ),
( 'HT', 'Haiti',                                     'Port-au-Prince'             ),
( 'HN', 'Honduras',                                  'Tegucigalpa'                ),
( 'HK', 'Hong Kong',                                 'Hong Kong'                  ),
( 'HR', 'Hrvatska',                                  'Zagreb'                     ),
( 'IN', 'Indija',                                    'New Delhi'                  ),
( 'ID', 'Indonezija',                                'Jakarta'                    ),
( 'IQ', 'Irak',                                      'Baghdad'                    ),
( 'IR', 'Iran',                                      'Tehran'                     ),
( 'IE', 'Irska',                                     'Dublin'                     ),
( 'IS', 'Island',                                    'Reykjavík'                  ),
( 'IT', 'Italija',                                   'Rome'                       ),
( 'IL', 'Izrael',                                    'Jerusalem'                  ),
( 'JM', 'Jamajka',                                   'Kingston'                   ),
( 'JP', 'Japan',                                     'Tokyo'                      ),
( 'YE', 'Jemen',                                     'Sanaá'                      ),
( 'JE', 'Jersey',                                    'St. Helier'                 ),
( 'JO', 'Jordan',                                    'Amman'                      ),
( 'GS', 'Južna Džordžija i Otoci Južni Sendvič',     'Grytviken'                  ),
( 'ZA', 'Južnoafrička Republika',                    'Pretoria'                   ),
( 'KY', 'Kajmanski otoci',                           'George Town'                ),
( 'KH', 'Kambodža',                                  'Phnom Penh'                 ),
( 'CM', 'Kamerun',                                   'Yaoundé'                    ),
( 'CA', 'Kanada',                                    'Ottawa'                     ),
( 'QA', 'Katar',                                     'Doha'                       ),
( 'KZ', 'Kazahstan',                                 'Astana'                     ),
( 'KE', 'Kenija',                                    'Nairobi'                    ),
( 'CN', 'Kina',                                      'Beijing'                    ),
( 'KG', 'Kirgistan',                                 'Bishkek'                    ),
( 'KI', 'Kiribati',                                  'South Tarawa'               ),
( 'CC', 'Kokosovi otoci (Keeling)',                  'West Island'                ),
( 'CO', 'Kolumbija',                                 'Bogotá'                     ),
( 'KM', 'Komori',                                    'Moroni'                     ),
( 'CG', 'Kongo',                                     'Brazzaville'                ),
( 'CD', 'Kongo, Demokratska Republika',              'Kinshasa'                   ),
( 'KP', 'Koreja, Demokratska Narodna Republika',     'Pyongyang'                  ),
( 'KR', 'Koreja, Republika',                         'Seoul'                      ),
( 'CR', 'Kostarika',                                 'San José'                   ),
( 'CU', 'Kuba',                                      'Havana'                     ),
( 'CK', 'Kukovi otoci',                              'Avarua'                     ),
( 'KW', 'Kuvajt',                                    'Kuwait City'                ),
( 'LA', 'Laos',                                      'Vientiane'                  ),
( 'LS', 'Lesoto',                                    'Maseru'                     ),
( 'LV', 'Letonija',                                  'Riga'                       ),
( 'LB', 'Libanon',                                   'Beirut'                     ),
( 'LR', 'Liberija',                                  'Monrovia'                   ),
( 'LY', 'Libija',                                    'Tripoli'                    ),
( 'LI', 'Liihtenštajn',                              'Vaduz'                      ),
( 'LT', 'Litva',                                     'Vilnius'                    ),
( 'LU', 'Luksemburg',                                'Luxembourg City'            ),
( 'MG', 'Madagaskar',                                'Antananarivo'               ),
( 'HU', 'Madžarska',                                 'Budapest'                   ),
( 'MO', 'Makao',                                     'Macau'                      ),
( 'MK', 'Makedonija',                                'Skopje'                     ),
( 'MW', 'Malavi',                                    'Lilongwe'                   ),
( 'MV', 'Maldivi',                                   'Malé'                       ),
( 'MY', 'Malezija',                                  'Kuala Lumpur'               ),
( 'ML', 'Mali',                                      'Bamako'                     ),
( 'MT', 'Malta',                                     'Valletta'                   ),
( 'MA', 'Maroko',                                    'Rabat'                      ),
( 'MH', 'Maršalovi Otoci',                           'Majuro'                     ),
( 'MQ', 'Martinique',                                'Fort-de-France'             ),
( 'MU', 'Mauricijus',                                'Port Louis'                 ),
( 'MR', 'Mauritanija',                               'Nouakchott'                 ),
( 'YT', 'Mayotte',                                   'Mamoudzou'                  ),
( 'MX', 'Meksiko',                                   'Mexico City'                ),
( 'MM', 'Mijanmar',                                  'Naypyidaw'                  ),
( 'FM', 'Mikronezija, Savezne države',               'Palikir'                    ),
( 'MD', 'Moldavija',                                 'Chisinau'                   ),
( 'MC', 'Monako',                                    'Monaco'                     ),
( 'MN', 'Mongolija',                                 'Ulaanbaatar'                ),
( 'MS', 'Montserrat',                                'Plymouth'                   ),
( 'MZ', 'Mozambik',                                  'Maputo'                     ),
( 'NA', 'Namibija',                                  'Windhoek'                   ),
( 'NR', 'Nauru',                                     'Yaren'                      ),
( 'NP', 'Nepal',                                     'Kathmandu'                  ),
( 'NE', 'Niger',                                     'Niamey'                     ),
( 'NG', 'Nigerija',                                  'Abuja'                      ),
( 'NI', 'Nikaragva',                                 'Managua'                    ),
( 'NU', 'Niue',                                      'Alofi'                      ),
( 'NL', 'Nizozemska',                                'Amsterdam'                  ),
( 'AN', 'Nizozemski Antili',                         'Willemstad'                 ),
( 'DE', 'Njemačka',                                  'Berlin'                     ),
( 'NO', 'Norveška',                                  'Oslo'                       ),
( 'NC', 'Nova Kaledonija',                           'Nouméa'                     ),
( 'NZ', 'Novi Zeland',                               'Wellington'                 ),
( 'CI', 'Obala Bjelokosti',                          'Yamoussoukro'               ),
( 'OM', 'Oman',                                      'Muscat'                     ),
( 'AX', 'Otoci Aland',                               'Mariehamn'                  ),
( 'HM', 'Otoci Heard i otoci McDonald',              NULL                         ),
( 'TC', 'Otoci Turks i Caicos',                      'Cockburn Town'              ),
( 'BV', 'Otok Bouvet',                               NULL                         ),
( 'IM', 'Otok Man',                                  'Douglas'                    ),
( 'NF', 'Otok Norfolk',                              'Kingston'                   ),
( 'PK', 'Pakistan',                                  'Islamabad'                  ),
( 'PW', 'Palau',                                     'Ngerulmud'                  ),
( 'PS', 'Palestina',                                 'Jerusalem'                  ),
( 'PA', 'Panama',                                    'Panama City'                ),
( 'PG', 'Papua Nova Gvineja',                        'Port Moresby'               ),
( 'PY', 'Paragvaj',                                  'Asunción'                   ),
( 'PE', 'Peru',                                      'Lima'                       ),
( 'PN', 'Pitcairn',                                  'Adamstown'                  ),
( 'PL', 'Poljska',                                   'Warsaw'                     ),
( 'PR', 'Portoriko',                                 'San Juan'                   ),
( 'PT', 'Portugal',                                  'Lisbon'                     ),
( 'RE', 'Réunion',                                   'Saint-Denis'                ),
( 'RW', 'Ruanda',                                    'Kigali'                     ),
( 'RO', 'Rumunjska',                                 'Bucharest'                  ),
( 'RU', 'Rusija',                                    'Moscow'                     ),
( 'US', 'SAD',                                       'Washington, D.C.'           ),
( 'SV', 'Salvador',                                  'San Salvador'               ),
( 'WS', 'Samoa',                                     'Apia'                       ),
( 'SM', 'San Marino',                                'San Marino'                 ),
( 'SA', 'Saudijska Arabija',                         'Riyadh'                     ),
( 'SC', 'Sejšeli',                                   'Victoria'                   ),
( 'SN', 'Senegal',                                   'Dakar'                      ),
( 'SL', 'Sijera Leone',                              'Freetown'                   ),
( 'SG', 'Singapore',                                 'Singapore'                  ),
( 'SY', 'Sirija',                                    'Damascus'                   ),
( 'MP', 'Sjeverni Marijanski Otoci',                 'Saipan'                     ),
( 'SK', 'Slovačka',                                  'Bratislava'                 ),
( 'SI', 'Slovenija',                                 'Ljubljana'                  ),
( 'SB', 'Solomonski Otoci',                          'Honiara'                    ),
( 'SO', 'Somalija',                                  'Mogadishu'                  ),
( 'ES', 'Španjolska',                                'Madrid'                     ),
( 'RS', 'Srbija',                                    'Belgrade'                   ),
( 'CF', 'Srednjoafrička Republika',                  'Bangui'                     ),
( 'LK', 'Šri Lanka',                                 'Sri Jayawardenepura'        ),
( 'SD', 'Sudan',                                     'Khartoum'                   ),
( 'SR', 'Surinam',                                   'Paramaribo'                 ),
( 'SJ', 'Svalbard i Jan Mayen',                      'Longyearbyen / Olonkinbyen' ),
( 'SZ', 'Svazi',                                     'Mbabane'                    ),
( 'SE', 'Švedska',                                   'Stockholm'                  ),
( 'SH', 'Sveta Helena',                              'Jamestown'                  ),
( 'LC', 'Sveta Lucija',                              'Castries'                   ),
( 'VA', 'Sveta Stolica (Država Vatikanskog Grada)',  'Vatican City'               ),
( 'BL', 'Sveti Bartolomej',                          'Gustavia'                   ),
( 'KN', 'Sveti Kristofor i Nevis',                   'Basseterre'                 ),
( 'MF', 'Sveti Martin',                              'Marigot'                    ),
( 'PM', 'Sveti Petar i Mikelon',                     'St. Pierre'                 ),
( 'ST', 'Sveti Toma i Prinsipe',                     'São Tomé'                   ),
( 'VC', 'Sveti Vincent i Grenadini',                 'Kingstown'                  ),
( 'CH', 'Švicarska',                                 'Bern'                       ),
( 'TJ', 'Tadžikistan',                               'Dushanbe'                   ),
( 'TH', 'Tajland',                                   'Bangkok'                    ),
( 'TW', 'Tajvan, Kineska Provincija',                'Taipei'                     ),
( 'TZ', 'Tanzanija, Ujedinjena Republika',           'Dodoma'                     ),
( 'TL', 'Timor Leste',                               'Dili'                       ),
( 'TG', 'Togo',                                      'Lomé'                       ),
( 'TK', 'Tokelau',                                   NULL                         ),
( 'TO', 'Tonga',                                     'Nukuʻalofa'                 ),
( 'TT', 'Trinidad i Tobago',                         'Port of Spain'              ),
( 'TN', 'Tunis',                                     'Tunis'                      ),
( 'TM', 'Turkmenistan',                              'Ashgabat'                   ),
( 'TR', 'Turkska',                                   'Ankara'                     ),
( 'TV', 'Tuvalu',                                    'Funafuti'                   ),
( 'UG', 'Uganda',                                    'Kampala'                    ),
( 'UM', 'Ujedinjene Države Manjih Pacifičkih Otoka', NULL                         ),
( 'AE', 'Ujedinjeni Arapski Emirati',                'Abu Dhabi'                  ),
( 'UA', 'Ukrajina',                                  'Kiev'                       ),
( 'UY', 'Urugvaj',                                   'Montevideo'                 ),
( 'UZ', 'Uzbekistan',                                'Tashkent'                   ),
( 'VU', 'Vanuatu',                                   'Port Vila'                  ),
( 'GB', 'Velika Britanija',                          'London'                     ),
( 'VE', 'Venezuela, Bolivarijanska Republika',       'Caracas'                    ),
( 'VN', 'Vijetnam',                                  'Hanoi'                      ),
( 'WF', 'Wallis i Futuna',                           'Mata-Utu'                   ),
( 'ZM', 'Zambija',                                   'Lusaka'                     ),
( 'EH', 'Zapadna Sahara',                            'El Aaiún'                   ),
( 'CV', 'Zelenortska Republika',                     'Praia'                      ),
( 'ZW', 'Zimbabve',                                  'Harare'                     );

CLUSTER iso.countries;
