package org.lby7.tables;

public enum Country
{
    AF( "AFG", (short)   4, "Afghanistan"                                  ),
    AX( "ALA", (short) 248, "Åland Islands"                                ),
    AL( "ALB", (short)   8, "Albania"                                      ),
    DZ( "DZA", (short)  12, "Algeria"                                      ),
    AS( "ASM", (short)  16, "American Samoa"                               ),
    AD( "AND", (short)  20, "Andorra"                                      ),
    AO( "AGO", (short)  24, "Angola"                                       ),
    AI( "AIA", (short) 660, "Anguilla"                                     ),
    AQ( "ATA", (short)  10, "Antarctica"                                   ),
    AG( "ATG", (short)  28, "Antigua and Barbuda"                          ),
    AR( "ARG", (short)  32, "Argentina"                                    ),
    AM( "ARM", (short)  51, "Armenia"                                      ),
    AW( "ABW", (short) 533, "Aruba"                                        ),
    AU( "AUS", (short)  36, "Australia"                                    ),
    AT( "AUT", (short)  40, "Austria"                                      ),
    AZ( "AZE", (short)  31, "Azerbaijan"                                   ),
    BS( "BHS", (short)  44, "Bahamas"                                      ),
    BH( "BHR", (short)  48, "Bahrain"                                      ),
    BD( "BGD", (short)  50, "Bangladesh"                                   ),
    BB( "BRB", (short)  52, "Barbados"                                     ),
    BY( "BLR", (short) 112, "Belarus"                                      ),
    BE( "BEL", (short)  56, "Belgium"                                      ),
    BZ( "BLZ", (short)  84, "Belize"                                       ),
    BJ( "BEN", (short) 204, "Benin"                                        ),
    BM( "BMU", (short)  60, "Bermuda"                                      ),
    BT( "BTN", (short)  64, "Bhutan"                                       ),
    BO( "BOL", (short)  68, "Bolivia, Plurinational State of"              ),
    BQ( "BES", (short) 535, "Bonaire, Saint Eustatius and Saba"            ),
    BA( "BIH", (short)  70, "Bosnia and Herzegovina"                       ),
    BW( "BWA", (short)  72, "Botswana"                                     ),
    BV( "BVT", (short)  74, "Bouvet Island"                                ),
    BR( "BRA", (short)  76, "Brazil"                                       ),
    IO( "IOT", (short)  86, "British Indian Ocean Territory"               ),
    BN( "BRN", (short)  96, "Brunei Darussalam"                            ),
    BG( "BGR", (short) 100, "Bulgaria"                                     ),
    BF( "BFA", (short) 854, "Burkina Faso"                                 ),
    BI( "BDI", (short) 108, "Burundi"                                      ),
    KH( "KHM", (short) 116, "Cambodia"                                     ),
    CM( "CMR", (short) 120, "Cameroon"                                     ),
    CA( "CAN", (short) 124, "Canada"                                       ),
    CV( "CPV", (short) 132, "Cape Verde"                                   ),
    KY( "CYM", (short) 136, "Cayman Islands"                               ),
    CF( "CAF", (short) 140, "Central African Republic"                     ),
    TD( "TCD", (short) 148, "Chad"                                         ),
    CL( "CHL", (short) 152, "Chile"                                        ),
    CN( "CHN", (short) 156, "China"                                        ),
    CX( "CXR", (short) 162, "Christmas Island"                             ),
    CC( "CCK", (short) 166, "Cocos (Keeling) Islands"                      ),
    CO( "COL", (short) 170, "Colombia"                                     ),
    KM( "COM", (short) 174, "Comoros"                                      ),
    CG( "COG", (short) 178, "Congo"                                        ),
    CD( "COD", (short) 180, "Congo, the Democratic Republic of the"        ),
    CK( "COK", (short) 184, "Cook Islands"                                 ),
    CR( "CRI", (short) 188, "Costa Rica"                                   ),
    CI( "CIV", (short) 384, "Côte d'Ivoire"                                ),
    HR( "HRV", (short) 191, "Croatia"                                      ),
    CU( "CUB", (short) 192, "Cuba"                                         ),
    CW( "CUW", (short) 531, "Curaçao"                                      ),
    CY( "CYP", (short) 196, "Cyprus"                                       ),
    CZ( "CZE", (short) 203, "Czech Republic"                               ),
    DK( "DNK", (short) 208, "Denmark"                                      ),
    DJ( "DJI", (short) 262, "Djibouti"                                     ),
    DM( "DMA", (short) 212, "Dominica"                                     ),
    DO( "DOM", (short) 214, "Dominican Republic"                           ),
    EC( "ECU", (short) 218, "Ecuador"                                      ),
    EG( "EGY", (short) 818, "Egypt"                                        ),
    SV( "SLV", (short) 222, "El Salvador"                                  ),
    GQ( "GNQ", (short) 226, "Equatorial Guinea"                            ),
    ER( "ERI", (short) 232, "Eritrea"                                      ),
    EE( "EST", (short) 233, "Estonia"                                      ),
    ET( "ETH", (short) 231, "Ethiopia"                                     ),
    FK( "FLK", (short) 238, "Falkland Islands (Malvinas)"                  ),
    FO( "FRO", (short) 234, "Faroe Islands"                                ),
    FJ( "FJI", (short) 242, "Fiji"                                         ),
    FI( "FIN", (short) 246, "Finland"                                      ),
    FR( "FRA", (short) 250, "France"                                       ),
    GF( "GUF", (short) 254, "French Guiana"                                ),
    PF( "PYF", (short) 258, "French Polynesia"                             ),
    TF( "ATF", (short) 260, "French Southern Territories"                  ),
    GA( "GAB", (short) 266, "Gabon"                                        ),
    GM( "GMB", (short) 270, "Gambia"                                       ),
    GE( "GEO", (short) 268, "Georgia"                                      ),
    DE( "DEU", (short) 276, "Germany"                                      ),
    GH( "GHA", (short) 288, "Ghana"                                        ),
    GI( "GIB", (short) 292, "Gibraltar"                                    ),
    GR( "GRC", (short) 300, "Greece"                                       ),
    GL( "GRL", (short) 304, "Greenland"                                    ),
    GD( "GRD", (short) 308, "Grenada"                                      ),
    GP( "GLP", (short) 312, "Guadeloupe"                                   ),
    GU( "GUM", (short) 316, "Guam"                                         ),
    GT( "GTM", (short) 320, "Guatemala"                                    ),
    GG( "GGY", (short) 831, "Guernsey"                                     ),
    GN( "GIN", (short) 324, "Guinea"                                       ),
    GW( "GNB", (short) 624, "Guinea-Bissau"                                ),
    GY( "GUY", (short) 328, "Guyana"                                       ),
    HT( "HTI", (short) 332, "Haiti"                                        ),
    HM( "HMD", (short) 334, "Heard Island and McDonald Islands"            ),
    VA( "VAT", (short) 336, "Holy See (Vatican City State)"                ),
    HN( "HND", (short) 340, "Honduras"                                     ),
    HK( "HKG", (short) 344, "Hong Kong"                                    ),
    HU( "HUN", (short) 348, "Hungary"                                      ),
    IS( "ISL", (short) 352, "Iceland"                                      ),
    IN( "IND", (short) 356, "India"                                        ),
    ID( "IDN", (short) 360, "Indonesia"                                    ),
    IR( "IRN", (short) 364, "Iran, Islamic Republic of"                    ),
    IQ( "IRQ", (short) 368, "Iraq"                                         ),
    IE( "IRL", (short) 372, "Ireland"                                      ),
    IM( "IMN", (short) 833, "Isle of Man"                                  ),
    IL( "ISR", (short) 376, "Israel"                                       ),
    IT( "ITA", (short) 380, "Italy"                                        ),
    JM( "JAM", (short) 388, "Jamaica"                                      ),
    JP( "JPN", (short) 392, "Japan"                                        ),
    JE( "JEY", (short) 832, "Jersey"                                       ),
    JO( "JOR", (short) 400, "Jordan"                                       ),
    KZ( "KAZ", (short) 398, "Kazakhstan"                                   ),
    KE( "KEN", (short) 404, "Kenya"                                        ),
    KI( "KIR", (short) 296, "Kiribati"                                     ),
    KP( "PRK", (short) 408, "Korea, Democratic People's Republic of"       ),
    KR( "KOR", (short) 410, "Korea, Republic of"                           ),
    KW( "KWT", (short) 414, "Kuwait"                                       ),
    KG( "KGZ", (short) 417, "Kyrgyzstan"                                   ),
    LA( "LAO", (short) 418, "Lao People's Democratic Republic"             ),
    LV( "LVA", (short) 428, "Latvia"                                       ),
    LB( "LBN", (short) 422, "Lebanon"                                      ),
    LS( "LSO", (short) 426, "Lesotho"                                      ),
    LR( "LBR", (short) 430, "Liberia"                                      ),
    LY( "LBY", (short) 434, "Libyan Arab Jamahiriya"                       ),
    LI( "LIE", (short) 438, "Liechtenstein"                                ),
    LT( "LTU", (short) 440, "Lithuania"                                    ),
    LU( "LUX", (short) 442, "Luxembourg"                                   ),
    MO( "MAC", (short) 446, "Macao"                                        ),
    MK( "MKD", (short) 807, "Macedonia, the former Yugoslav Republic of"   ),
    MG( "MDG", (short) 450, "Madagascar"                                   ),
    MW( "MWI", (short) 454, "Malawi"                                       ),
    MY( "MYS", (short) 458, "Malaysia"                                     ),
    MV( "MDV", (short) 462, "Maldives"                                     ),
    ML( "MLI", (short) 466, "Mali"                                         ),
    MT( "MLT", (short) 470, "Malta"                                        ),
    MH( "MHL", (short) 584, "Marshall Islands"                             ),
    MQ( "MTQ", (short) 474, "Martinique"                                   ),
    MR( "MRT", (short) 478, "Mauritania"                                   ),
    MU( "MUS", (short) 480, "Mauritius"                                    ),
    YT( "MYT", (short) 175, "Mayotte"                                      ),
    MX( "MEX", (short) 484, "Mexico"                                       ),
    FM( "FSM", (short) 583, "Micronesia, Federated States of"              ),
    MD( "MDA", (short) 498, "Moldova, Republic of"                         ),
    MC( "MCO", (short) 492, "Monaco"                                       ),
    MN( "MNG", (short) 496, "Mongolia"                                     ),
    ME( "MNE", (short) 499, "Montenegro"                                   ),
    MS( "MSR", (short) 500, "Montserrat"                                   ),
    MA( "MAR", (short) 504, "Morocco"                                      ),
    MZ( "MOZ", (short) 508, "Mozambique"                                   ),
    MM( "MMR", (short) 104, "Myanmar"                                      ),
    NA( "NAM", (short) 516, "Namibia"                                      ),
    NR( "NRU", (short) 520, "Nauru"                                        ),
    NP( "NPL", (short) 524, "Nepal"                                        ),
    NL( "NLD", (short) 528, "Netherlands"                                  ),
    NC( "NCL", (short) 540, "New Caledonia"                                ),
    NZ( "NZL", (short) 554, "New Zealand"                                  ),
    NI( "NIC", (short) 558, "Nicaragua"                                    ),
    NE( "NER", (short) 562, "Niger"                                        ),
    NG( "NGA", (short) 566, "Nigeria"                                      ),
    NU( "NIU", (short) 570, "Niue"                                         ),
    NF( "NFK", (short) 574, "Norfolk Island"                               ),
    MP( "MNP", (short) 580, "Northern Mariana Islands"                     ),
    NO( "NOR", (short) 578, "Norway"                                       ),
    OM( "OMN", (short) 512, "Oman"                                         ),
    PK( "PAK", (short) 586, "Pakistan"                                     ),
    PW( "PLW", (short) 585, "Palau"                                        ),
    PS( "PSE", (short) 275, "Palestinian Territory, Occupied"              ),
    PA( "PAN", (short) 591, "Panama"                                       ),
    PG( "PNG", (short) 598, "Papua New Guinea"                             ),
    PY( "PRY", (short) 600, "Paraguay"                                     ),
    PE( "PER", (short) 604, "Peru"                                         ),
    PH( "PHL", (short) 608, "Philippines"                                  ),
    PN( "PCN", (short) 612, "Pitcairn"                                     ),
    PL( "POL", (short) 616, "Poland"                                       ),
    PT( "PRT", (short) 620, "Portugal"                                     ),
    PR( "PRI", (short) 630, "Puerto Rico"                                  ),
    QA( "QAT", (short) 634, "Qatar"                                        ),
    RE( "REU", (short) 638, "Réunion"                                      ),
    RO( "ROU", (short) 642, "Romania"                                      ),
    RU( "RUS", (short) 643, "Russian Federation"                           ),
    RW( "RWA", (short) 646, "Rwanda"                                       ),
    BL( "BLM", (short) 652, "Saint Barthélemy"                             ),
    SH( "SHN", (short) 654, "Saint Helena, Ascension and Tristan da Cunha" ),
    KN( "KNA", (short) 659, "Saint Kitts and Nevis"                        ),
    LC( "LCA", (short) 662, "Saint Lucia"                                  ),
    MF( "MAF", (short) 663, "Saint Martin (French part)"                   ),
    PM( "SPM", (short) 666, "Saint Pierre and Miquelon"                    ),
    VC( "VCT", (short) 670, "Saint Vincent and the Grenadines"             ),
    WS( "WSM", (short) 882, "Samoa"                                        ),
    SM( "SMR", (short) 674, "San Marino"                                   ),
    ST( "STP", (short) 678, "Sao Tome and Principe"                        ),
    SA( "SAU", (short) 682, "Saudi Arabia"                                 ),
    SN( "SEN", (short) 686, "Senegal"                                      ),
    RS( "SRB", (short) 688, "Serbia"                                       ),
    SC( "SYC", (short) 690, "Seychelles"                                   ),
    SL( "SLE", (short) 694, "Sierra Leone"                                 ),
    SG( "SGP", (short) 702, "Singapore"                                    ),
    SX( "SXM", (short) 534, "Sint Maarten (Dutch part)"                    ),
    SK( "SVK", (short) 703, "Slovakia"                                     ),
    SI( "SVN", (short) 705, "Slovenia"                                     ),
    SB( "SLB", (short)  90, "Solomon Islands"                              ),
    SO( "SOM", (short) 706, "Somalia"                                      ),
    ZA( "ZAF", (short) 710, "South Africa"                                 ),
    GS( "SGS", (short) 239, "South Georgia and the South Sandwich Islands" ),
    ES( "ESP", (short) 724, "Spain"                                        ),
    LK( "LKA", (short) 144, "Sri Lanka"                                    ),
    SD( "SDN", (short) 736, "Sudan"                                        ),
    SR( "SUR", (short) 740, "Suriname"                                     ),
    SJ( "SJM", (short) 744, "Svalbard and Jan Mayen"                       ),
    SZ( "SWZ", (short) 748, "Swaziland"                                    ),
    SE( "SWE", (short) 752, "Sweden"                                       ),
    CH( "CHE", (short) 756, "Switzerland"                                  ),
    SY( "SYR", (short) 760, "Syrian Arab Republic"                         ),
    TW( "TWN", (short) 158, "Taiwan, Province of China"                    ),
    TJ( "TJK", (short) 762, "Tajikistan"                                   ),
    TZ( "TZA", (short) 834, "Tanzania, United Republic of"                 ),
    TH( "THA", (short) 764, "Thailand"                                     ),
    TL( "TLS", (short) 626, "Timor-Leste"                                  ),
    TG( "TGO", (short) 768, "Togo"                                         ),
    TK( "TKL", (short) 772, "Tokelau"                                      ),
    TO( "TON", (short) 776, "Tonga"                                        ),
    TT( "TTO", (short) 780, "Trinidad and Tobago"                          ),
    TN( "TUN", (short) 788, "Tunisia"                                      ),
    TR( "TUR", (short) 792, "Turkey"                                       ),
    TM( "TKM", (short) 795, "Turkmenistan"                                 ),
    TC( "TCA", (short) 796, "Turks and Caicos Islands"                     ),
    TV( "TUV", (short) 798, "Tuvalu"                                       ),
    UG( "UGA", (short) 800, "Uganda"                                       ),
    UA( "UKR", (short) 804, "Ukraine"                                      ),
    AE( "ARE", (short) 784, "United Arab Emirates"                         ),
    GB( "GBR", (short) 826, "United Kingdom"                               ),
    US( "USA", (short) 840, "United States"                                ),
    UM( "UMI", (short) 581, "United States Minor Outlying Islands"         ),
    UY( "URY", (short) 858, "Uruguay"                                      ),
    UZ( "UZB", (short) 860, "Uzbekistan"                                   ),
    VU( "VUT", (short) 548, "Vanuatu"                                      ),
    VE( "VEN", (short) 862, "Venezuela, Bolivarian Republic of"            ),
    VN( "VNM", (short) 704, "Viet Nam"                                     ),
    VG( "VGB", (short)  92, "Virgin Islands, British"                      ),
    VI( "VIR", (short) 850, "Virgin Islands, U.S."                         ),
    WF( "WLF", (short) 876, "Wallis and Futuna"                            ),
    EH( "ESH", (short) 732, "Western Sahara"                               ),
    YE( "YEM", (short) 887, "Yemen"                                        ),
    ZM( "ZMB", (short) 894, "Zambia"                                       ),
    ZW( "ZWE", (short) 716, "Zimbabwe"                                     );

    public final String a2, a3, n3;
    public final String isoName, wikiName;

    private Country( final String a3, final short n3, final String wikiName )
    {
        this.a2 = name();
        this.a3 = a3;
        this.n3 = String.format( "%03d", n3 );
        this.isoName = wikiName.toUpperCase();
        this.wikiName = wikiName;
    }
}