DROP SCHEMA IF EXISTS iso CASCADE;

CREATE SCHEMA iso;
COMMENT ON SCHEMA iso IS 'ISO tables (read-only)';

CREATE TABLE iso.countries
(
	alpha2_code text NOT NULL
		CONSTRAINT pk_iso_countries_alpha2_code PRIMARY KEY WITH(FILLFACTOR=100)
		CONSTRAINT ck_iso_countries_alpha2_code CHECK(alpha2_code~'^[A-Z]{2}$'),
	alpha3_code text
		CONSTRAINT uq_iso_countries_alpha3_code UNIQUE WITH(FILLFACTOR=100)
		CONSTRAINT ck_iso_countries_alpha3_code CHECK(alpha3_code~'^[A-Z]{3}$'),
	numeric3_code text
		CONSTRAINT uq_iso_countries_numeric3_code UNIQUE WITH(FILLFACTOR=100)
		CONSTRAINT ck_iso_countries_numeric3_code CHECK(numeric3_code~'^\d{3}$'),
	iso_name text NOT NULL
		CONSTRAINT uq_iso_countries_iso_name UNIQUE WITH(FILLFACTOR=100)
)
WITH(FILLFACTOR=100);

COMMENT ON TABLE iso.countries IS 'ISO 3166-1: Codes for countries, dependent territories, and special areas of geographical interest';
COMMENT ON COLUMN iso.countries.alpha2_code IS 'PK: Two-letter country code';
COMMENT ON COLUMN iso.countries.alpha3_code IS 'UQ: Three-letter country code';
COMMENT ON COLUMN iso.countries.numeric3_code IS 'UQ: Three-digit country code';
COMMENT ON COLUMN iso.countries.iso_name IS 'UQ: ISO country name';

ALTER TABLE iso.countries CLUSTER ON uq_iso_countries_iso_name;

INSERT INTO iso.countries(alpha2_code,alpha3_code,numeric3_code,iso_name)VALUES
( 'AF', 'AFG', '004', 'AFGHANISTAN'                                  ),
( 'AX', 'ALA', '248', 'ÅLAND ISLANDS'                                ),
( 'AL', 'ALB', '008', 'ALBANIA'                                      ),
( 'DZ', 'DZA', '012', 'ALGERIA'                                      ),
( 'AS', 'ASM', '016', 'AMERICAN SAMOA'                               ),
( 'AD', 'AND', '020', 'ANDORRA'                                      ),
( 'AO', 'AGO', '024', 'ANGOLA'                                       ),
( 'AI', 'AIA', '660', 'ANGUILLA'                                     ),
( 'AQ', 'ATA', '010', 'ANTARCTICA'                                   ),
( 'AG', 'ATG', '028', 'ANTIGUA AND BARBUDA'                          ),
( 'AR', 'ARG', '032', 'ARGENTINA'                                    ),
( 'AM', 'ARM', '051', 'ARMENIA'                                      ),
( 'AW', 'ABW', '533', 'ARUBA'                                        ),
( 'AU', 'AUS', '036', 'AUSTRALIA'                                    ),
( 'AT', 'AUT', '040', 'AUSTRIA'                                      ),
( 'AZ', 'AZE', '031', 'AZERBAIJAN'                                   ),
( 'BS', 'BHS', '044', 'BAHAMAS'                                      ),
( 'BH', 'BHR', '048', 'BAHRAIN'                                      ),
( 'BD', 'BGD', '050', 'BANGLADESH'                                   ),
( 'BB', 'BRB', '052', 'BARBADOS'                                     ),
( 'BY', 'BLR', '112', 'BELARUS'                                      ),
( 'BE', 'BEL', '056', 'BELGIUM'                                      ),
( 'BZ', 'BLZ', '084', 'BELIZE'                                       ),
( 'BJ', 'BEN', '204', 'BENIN'                                        ),
( 'BM', 'BMU', '060', 'BERMUDA'                                      ),
( 'BT', 'BTN', '064', 'BHUTAN'                                       ),
( 'BO', 'BOL', '068', 'BOLIVIA, PLURINATIONAL STATE OF'              ),
( 'BA', 'BIH', '070', 'BOSNIA AND HERZEGOVINA'                       ),
( 'BW', 'BWA', '072', 'BOTSWANA'                                     ),
( 'BV', 'BVT', '074', 'BOUVET ISLAND'                                ),
( 'BR', 'BRA', '076', 'BRAZIL'                                       ),
( 'IO', 'IOT', '086', 'BRITISH INDIAN OCEAN TERRITORY'               ),
( 'BN', 'BRN', '096', 'BRUNEI DARUSSALAM'                            ),
( 'BG', 'BGR', '100', 'BULGARIA'                                     ),
( 'BF', 'BFA', '854', 'BURKINA FASO'                                 ),
( 'BI', 'BDI', '108', 'BURUNDI'                                      ),
( 'KH', 'KHM', '116', 'CAMBODIA'                                     ),
( 'CM', 'CMR', '120', 'CAMEROON'                                     ),
( 'CA', 'CAN', '124', 'CANADA'                                       ),
( 'CV', 'CPV', '132', 'CAPE VERDE'                                   ),
( 'KY', 'CYM', '136', 'CAYMAN ISLANDS'                               ),
( 'CF', 'CAF', '140', 'CENTRAL AFRICAN REPUBLIC'                     ),
( 'TD', 'TCD', '148', 'CHAD'                                         ),
( 'CL', 'CHL', '152', 'CHILE'                                        ),
( 'CN', 'CHN', '156', 'CHINA'                                        ),
( 'CX', 'CXR', '162', 'CHRISTMAS ISLAND'                             ),
( 'CC', 'CCK', '166', 'COCOS (KEELING) ISLANDS'                      ),
( 'CO', 'COL', '170', 'COLOMBIA'                                     ),
( 'KM', 'COM', '174', 'COMOROS'                                      ),
( 'CG', 'COG', '178', 'CONGO'                                        ),
( 'CD', 'COD', '180', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE'        ),
( 'CK', 'COK', '184', 'COOK ISLANDS'                                 ),
( 'CR', 'CRI', '188', 'COSTA RICA'                                   ),
( 'CI', 'CIV', '384', 'CÔTE D''IVOIRE'                               ),
( 'HR', 'HRV', '191', 'CROATIA'                                      ),
( 'CU', 'CUB', '192', 'CUBA'                                         ),
( 'CY', 'CYP', '196', 'CYPRUS'                                       ),
( 'CZ', 'CZE', '203', 'CZECH REPUBLIC'                               ),
( 'DK', 'DNK', '208', 'DENMARK'                                      ),
( 'DJ', 'DJI', '262', 'DJIBOUTI'                                     ),
( 'DM', 'DMA', '212', 'DOMINICA'                                     ),
( 'DO', 'DOM', '214', 'DOMINICAN REPUBLIC'                           ),
( 'EC', 'ECU', '218', 'ECUADOR'                                      ),
( 'EG', 'EGY', '818', 'EGYPT'                                        ),
( 'SV', 'SLV', '222', 'EL SALVADOR'                                  ),
( 'GQ', 'GNQ', '226', 'EQUATORIAL GUINEA'                            ),
( 'ER', 'ERI', '232', 'ERITREA'                                      ),
( 'EE', 'EST', '233', 'ESTONIA'                                      ),
( 'ET', 'ETH', '231', 'ETHIOPIA'                                     ),
( 'FK', 'FLK', '238', 'FALKLAND ISLANDS (MALVINAS)'                  ),
( 'FO', 'FRO', '234', 'FAROE ISLANDS'                                ),
( 'FJ', 'FJI', '242', 'FIJI'                                         ),
( 'FI', 'FIN', '246', 'FINLAND'                                      ),
( 'FR', 'FRA', '250', 'FRANCE'                                       ),
( 'GF', 'GUF', '254', 'FRENCH GUIANA'                                ),
( 'PF', 'PYF', '258', 'FRENCH POLYNESIA'                             ),
( 'TF', 'ATF', '260', 'FRENCH SOUTHERN TERRITORIES'                  ),
( 'GA', 'GAB', '266', 'GABON'                                        ),
( 'GM', 'GMB', '270', 'GAMBIA'                                       ),
( 'GE', 'GEO', '268', 'GEORGIA'                                      ),
( 'DE', 'DEU', '276', 'GERMANY'                                      ),
( 'GH', 'GHA', '288', 'GHANA'                                        ),
( 'GI', 'GIB', '292', 'GIBRALTAR'                                    ),
( 'GR', 'GRC', '300', 'GREECE'                                       ),
( 'GL', 'GRL', '304', 'GREENLAND'                                    ),
( 'GD', 'GRD', '308', 'GRENADA'                                      ),
( 'GP', 'GLP', '312', 'GUADELOUPE'                                   ),
( 'GU', 'GUM', '316', 'GUAM'                                         ),
( 'GT', 'GTM', '320', 'GUATEMALA'                                    ),
( 'GG', 'GGY', '831', 'GUERNSEY'                                     ),
( 'GN', 'GIN', '324', 'GUINEA'                                       ),
( 'GW', 'GNB', '624', 'GUINEA-BISSAU'                                ),
( 'GY', 'GUY', '328', 'GUYANA'                                       ),
( 'HT', 'HTI', '332', 'HAITI'                                        ),
( 'HM', 'HMD', '334', 'HEARD ISLAND AND MCDONALD ISLANDS'            ),
( 'VA', 'VAT', '336', 'HOLY SEE (VATICAN CITY STATE)'                ),
( 'HN', 'HND', '340', 'HONDURAS'                                     ),
( 'HK', 'HKG', '344', 'HONG KONG'                                    ),
( 'HU', 'HUN', '348', 'HUNGARY'                                      ),
( 'IS', 'ISL', '352', 'ICELAND'                                      ),
( 'IN', 'IND', '356', 'INDIA'                                        ),
( 'ID', 'IDN', '360', 'INDONESIA'                                    ),
( 'IR', 'IRN', '364', 'IRAN, ISLAMIC REPUBLIC OF'                    ),
( 'IQ', 'IRQ', '368', 'IRAQ'                                         ),
( 'IE', 'IRL', '372', 'IRELAND'                                      ),
( 'IM', 'IMN', '833', 'ISLE OF MAN'                                  ),
( 'IL', 'ISR', '376', 'ISRAEL'                                       ),
( 'IT', 'ITA', '380', 'ITALY'                                        ),
( 'JM', 'JAM', '388', 'JAMAICA'                                      ),
( 'JP', 'JPN', '392', 'JAPAN'                                        ),
( 'JE', 'JEY', '832', 'JERSEY'                                       ),
( 'JO', 'JOR', '400', 'JORDAN'                                       ),
( 'KZ', 'KAZ', '398', 'KAZAKHSTAN'                                   ),
( 'KE', 'KEN', '404', 'KENYA'                                        ),
( 'KI', 'KIR', '296', 'KIRIBATI'                                     ),
( 'KW', 'KWT', '414', 'KUWAIT'                                       ),
( 'KG', 'KGZ', '417', 'KYRGYZSTAN'                                   ),
( 'LA', 'LAO', '418', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC'            ),
( 'LV', 'LVA', '428', 'LATVIA'                                       ),
( 'LB', 'LBN', '422', 'LEBANON'                                      ),
( 'LS', 'LSO', '426', 'LESOTHO'                                      ),
( 'LR', 'LBR', '430', 'LIBERIA'                                      ),
( 'LY', 'LBY', '434', 'LIBYAN ARAB JAMAHIRIYA'                       ),
( 'LI', 'LIE', '438', 'LIECHTENSTEIN'                                ),
( 'LT', 'LTU', '440', 'LITHUANIA'                                    ),
( 'LU', 'LUX', '442', 'LUXEMBOURG'                                   ),
( 'MO', 'MAC', '446', 'MACAO'                                        ),
( 'MK', 'MKD', '807', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'   ),
( 'MG', 'MDG', '450', 'MADAGASCAR'                                   ),
( 'MW', 'MWI', '454', 'MALAWI'                                       ),
( 'MY', 'MYS', '458', 'MALAYSIA'                                     ),
( 'MV', 'MDV', '462', 'MALDIVES'                                     ),
( 'ML', 'MLI', '466', 'MALI'                                         ),
( 'MT', 'MLT', '470', 'MALTA'                                        ),
( 'MH', 'MHL', '584', 'MARSHALL ISLANDS'                             ),
( 'MQ', 'MTQ', '474', 'MARTINIQUE'                                   ),
( 'MR', 'MRT', '478', 'MAURITANIA'                                   ),
( 'MU', 'MUS', '480', 'MAURITIUS'                                    ),
( 'YT', 'MYT', '175', 'MAYOTTE'                                      ),
( 'MX', 'MEX', '484', 'MEXICO'                                       ),
( 'FM', 'FSM', '583', 'MICRONESIA, FEDERATED STATES OF'              ),
( 'MD', 'MDA', '498', 'MOLDOVA, REPUBLIC OF'                         ),
( 'MC', 'MCO', '492', 'MONACO'                                       ),
( 'MN', 'MNG', '496', 'MONGOLIA'                                     ),
( 'ME', 'MNE', '499', 'MONTENEGRO'                                   ),
( 'MS', 'MSR', '500', 'MONTSERRAT'                                   ),
( 'MA', 'MAR', '504', 'MOROCCO'                                      ),
( 'MZ', 'MOZ', '508', 'MOZAMBIQUE'                                   ),
( 'MM', 'MMR', '104', 'MYANMAR'                                      ),
( 'NA', 'NAM', '516', 'NAMIBIA'                                      ),
( 'NR', 'NRU', '520', 'NAURU'                                        ),
( 'NP', 'NPL', '524', 'NEPAL'                                        ),
( 'NL', 'NLD', '528', 'NETHERLANDS'                                  ),
( 'AN', 'ANT', '530', 'NETHERLANDS ANTILLES'                         ),
( 'NC', 'NCL', '540', 'NEW CALEDONIA'                                ),
( 'NZ', 'NZL', '554', 'NEW ZEALAND'                                  ),
( 'NI', 'NIC', '558', 'NICARAGUA'                                    ),
( 'NE', 'NER', '562', 'NIGER'                                        ),
( 'NG', 'NGA', '566', 'NIGERIA'                                      ),
( 'NU', 'NIU', '570', 'NIUE'                                         ),
( 'NF', 'NFK', '574', 'NORFOLK ISLAND'                               ),
( 'MP', 'MNP', '580', 'NORTHERN MARIANA ISLANDS'                     ),
( 'KP', 'PRK', '408', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF'      ),
( 'NO', 'NOR', '578', 'NORWAY'                                       ),
( 'OM', 'OMN', '512', 'OMAN'                                         ),
( 'PK', 'PAK', '586', 'PAKISTAN'                                     ),
( 'PW', 'PLW', '585', 'PALAU'                                        ),
( 'PS', 'PSE', '275', 'PALESTINIAN TERRITORY, OCCUPIED'              ),
( 'PA', 'PAN', '591', 'PANAMA'                                       ),
( 'PG', 'PNG', '598', 'PAPUA NEW GUINEA'                             ),
( 'PY', 'PRY', '600', 'PARAGUAY'                                     ),
( 'PE', 'PER', '604', 'PERU'                                         ),
( 'PH', 'PHL', '608', 'PHILIPPINES'                                  ),
( 'PN', 'PCN', '612', 'PITCAIRN'                                     ),
( 'PL', 'POL', '616', 'POLAND'                                       ),
( 'PT', 'PRT', '620', 'PORTUGAL'                                     ),
( 'PR', 'PRI', '630', 'PUERTO RICO'                                  ),
( 'QA', 'QAT', '634', 'QATAR'                                        ),
( 'RE', 'REU', '638', 'REUNION'                                      ),
( 'RO', 'ROU', '642', 'ROMANIA'                                      ),
( 'RU', 'RUS', '643', 'RUSSIAN FEDERATION'                           ),
( 'RW', 'RWA', '646', 'RWANDA'                                       ),
( 'BL', 'BLM', '652', 'SAINT BARTHÉLEMY'                             ),
( 'SH', 'SHN', '654', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA' ),
( 'KN', 'KNA', '659', 'SAINT KITTS AND NEVIS'                        ),
( 'LC', 'LCA', '662', 'SAINT LUCIA'                                  ),
( 'MF', 'MAF', '663', 'SAINT MARTIN'                                 ),
( 'PM', 'SPM', '666', 'SAINT PIERRE AND MIQUELON'                    ),
( 'VC', 'VCT', '670', 'SAINT VINCENT AND THE GRENADINES'             ),
( 'WS', 'WSM', '882', 'SAMOA'                                        ),
( 'SM', 'SMR', '674', 'SAN MARINO'                                   ),
( 'ST', 'STP', '678', 'SAO TOME AND PRINCIPE'                        ),
( 'SA', 'SAU', '682', 'SAUDI ARABIA'                                 ),
( 'SN', 'SEN', '686', 'SENEGAL'                                      ),
( 'RS', 'SRB', '688', 'SERBIA'                                       ),
( 'SC', 'SYC', '690', 'SEYCHELLES'                                   ),
( 'SL', 'SLE', '694', 'SIERRA LEONE'                                 ),
( 'SG', 'SGP', '702', 'SINGAPORE'                                    ),
( 'SK', 'SVK', '703', 'SLOVAKIA'                                     ),
( 'SI', 'SVN', '705', 'SLOVENIA'                                     ),
( 'SB', 'SLB', '090', 'SOLOMON ISLANDS'                              ),
( 'SO', 'SOM', '706', 'SOMALIA'                                      ),
( 'ZA', 'ZAF', '710', 'SOUTH AFRICA'                                 ),
( 'GS', 'SGS', '239', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' ),
( 'KR', 'KOR', '410', 'KOREA, REPUBLIC OF'                           ),
( 'ES', 'ESP', '724', 'SPAIN'                                        ),
( 'LK', 'LKA', '144', 'SRI LANKA'                                    ),
( 'SD', 'SDN', '736', 'SUDAN'                                        ),
( 'SR', 'SUR', '740', 'SURINAME'                                     ),
( 'SJ', 'SJM', '744', 'SVALBARD AND JAN MAYEN'                       ),
( 'SZ', 'SWZ', '748', 'SWAZILAND'                                    ),
( 'SE', 'SWE', '752', 'SWEDEN'                                       ),
( 'CH', 'CHE', '756', 'SWITZERLAND'                                  ),
( 'SY', 'SYR', '760', 'SYRIAN ARAB REPUBLIC'                         ),
( 'TW', 'TWN', '158', 'TAIWAN, PROVINCE OF CHINA'                    ),
( 'TJ', 'TJK', '762', 'TAJIKISTAN'                                   ),
( 'TZ', 'TZA', '834', 'TANZANIA, UNITED REPUBLIC OF'                 ),
( 'TH', 'THA', '764', 'THAILAND'                                     ),
( 'TL', 'TLS', '626', 'TIMOR-LESTE'                                  ),
( 'TG', 'TGO', '768', 'TOGO'                                         ),
( 'TK', 'TKL', '772', 'TOKELAU'                                      ),
( 'TO', 'TON', '776', 'TONGA'                                        ),
( 'TT', 'TTO', '780', 'TRINIDAD AND TOBAGO'                          ),
( 'TN', 'TUN', '788', 'TUNISIA'                                      ),
( 'TR', 'TUR', '792', 'TURKEY'                                       ),
( 'TM', 'TKM', '795', 'TURKMENISTAN'                                 ),
( 'TC', 'TCA', '796', 'TURKS AND CAICOS ISLANDS'                     ),
( 'TV', 'TUV', '798', 'TUVALU'                                       ),
( 'UG', 'UGA', '800', 'UGANDA'                                       ),
( 'UA', 'UKR', '804', 'UKRAINE'                                      ),
( 'AE', 'ARE', '784', 'UNITED ARAB EMIRATES'                         ),
( 'GB', 'GBR', '826', 'UNITED KINGDOM'                               ),
( 'US', 'USA', '840', 'UNITED STATES'                                ),
( 'UM', 'UMI', '581', 'UNITED STATES MINOR OUTLYING ISLANDS'         ),
( 'UY', 'URY', '858', 'URUGUAY'                                      ),
( 'UZ', 'UZB', '860', 'UZBEKISTAN'                                   ),
( 'VU', 'VUT', '548', 'VANUATU'                                      ),
( 'VE', 'VEN', '862', 'VENEZUELA, BOLIVARIAN REPUBLIC OF'            ),
( 'VN', 'VNM', '704', 'VIET NAM'                                     ),
( 'VG', 'VGB', '092', 'VIRGIN ISLANDS, BRITISH'                      ),
( 'VI', 'VIR', '850', 'VIRGIN ISLANDS, U.S.'                         ),
( 'WF', 'WLF', '876', 'WALLIS AND FUTUNA'                            ),
( 'EH', 'ESH', '732', 'WESTERN SAHARA'                               ),
( 'YE', 'YEM', '887', 'YEMEN'                                        ),
( 'ZM', 'ZMB', '894', 'ZAMBIA'                                       ),
( 'ZW', 'ZWE', '716', 'ZIMBABWE'                                     );

CLUSTER iso.countries;
